# dev开发环境 debug测试环境 prod线上环境
mode: dev
application:
  # 服务器ip，默认使用 0.0.0.0
  host: 0.0.0.0
  # 服务名称
  name: testApp
  # 端口号
  port: 8000 # 服务端口号
  readtimeout: 1
  writertimeout: 2
  # 数据权限功能开关
  enabledp: false
logger:
  level: debug  # debug, info, warn, error, dpanic, panic, fatal
  format: json
  encodeLevel: LowercaseLevelEncoder
  inConsole: true
  Path: temp

  enableddb: false

jwt:
  # token 密钥，生产环境时及的修改
  secret: go-admin
  # token 过期时间 单位：秒
  timeout: 3600
database:
  # 数据库类型 mysql，sqlite3， postgres
  driver: mysql
  # 数据库连接字符串 mysql 缺省信息 charset=utf8&parseTime=True&loc=Local&timeout=1000ms
  source: root:catmaotu@tcp(127.0.0.1:3306)/goadmin?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
gen:
  # 代码生成读取的数据库名称
  dbname: goadmin
  # 代码生成是使用前端代码存放位置，需要指定到src文件夹，相对路径
  frontpath: ../go-admin-ui/src
