package gorm

import (
	"gorm.io/gorm"

	"github.com/x-tardis/go-admin/app/models"
)

func InitData(db *gorm.DB) {
	list := []models.CasbinRule{
		{"p", "admin", "/api/v1/menus", "GET", "", "", ""},
		{"p", "admin", "/api/v1/menus/:id", "GET", "", "", ""},
		{"p", "admin", "/api/v1/menus", "POST", "", "", ""},
		{"p", "admin", "/api/v1/menus", "PUT", "", "", ""},
		{"p", "admin", "/api/v1/menus/:id", "DELETE", "", "", ""},
		{"p", "admin", "/api/v1/users", "GET", "", "", ""},
		{"p", "admin", "/api/v1/users/:id", "GET", "", "", ""},
		{"p", "admin", "/api/v1/users/", "GET", "", "", ""},
		{"p", "admin", "/api/v1/users", "POST", "", "", ""},
		{"p", "admin", "/api/v1/users", "PUT", "", "", ""},
		{"p", "admin", "/api/v1/users/:id", "DELETE", "", "", ""},
		{"p", "admin", "/api/v1/user/profile", "GET", "", "", ""},
		{"p", "admin", "/api/v1/roles", "GET", "", "", ""},
		{"p", "admin", "/api/v1/roles/:id", "GET", "", "", ""},
		{"p", "admin", "/api/v1/roles", "POST", "", "", ""},
		{"p", "admin", "/api/v1/roles", "PUT", "", "", ""},
		{"p", "admin", "/api/v1/roles/:id", "DELETE", "", "", ""},
		{"p", "admin", "/api/v1/configs", "GET", "", "", ""},
		{"p", "admin", "/api/v1/configs/:id", "GET", "", "", ""},
		{"p", "admin", "/api/v1/configs", "POST", "", "", ""},
		{"p", "admin", "/api/v1/configs", "PUT", "", "", ""},
		{"p", "admin", "/api/v1/configs/:id", "DELETE", "", "", ""},
		{"p", "admin", "/api/v1/menurole", "GET", "", "", ""},
		{"p", "admin", "/api/v1/roleMenuTreeselect/:id", "GET", "", "", ""},
		{"p", "admin", "/api/v1/menuTreeselect", "GET", "", "", ""},
		{"p", "admin", "/api/v1/rolemenu", "GET", "", "", ""},
		{"p", "admin", "/api/v1/rolemenu", "POST", "", "", ""},
		{"p", "admin", "/api/v1/rolemenu/:id", "DELETE", "", "", ""},
		{"p", "admin", "/api/v1/depts", "GET", "", "", ""},
		{"p", "admin", "/api/v1/depts/:id", "GET", "", "", ""},
		{"p", "admin", "/api/v1/depts", "POST", "", "", ""},
		{"p", "admin", "/api/v1/depts", "PUT", "", "", ""},
		{"p", "admin", "/api/v1/depts/:id", "DELETE", "", "", ""},
		{"p", "admin", "/api/v1/dict/databytype/", "GET", "", "", ""},
		{"p", "admin", "/api/v1/dict/datalist", "GET", "", "", ""},
		{"p", "admin", "/api/v1/dict/data/:id", "GET", "", "", ""},
		{"p", "admin", "/api/v1/dict/databytype/:id", "GET", "", "", ""},
		{"p", "admin", "/api/v1/dict/data", "POST", "", "", ""},
		{"p", "admin", "/api/v1/dict/data/", "PUT", "", "", ""},
		{"p", "admin", "/api/v1/dict/data/:id", "DELETE", "", "", ""},
		{"p", "admin", "/api/v1/dict/typelist", "GET", "", "", ""},
		{"p", "admin", "/api/v1/dict/type/:id", "GET", "", "", ""},
		{"p", "admin", "/api/v1/dict/type", "POST", "", "", ""},
		{"p", "admin", "/api/v1/dict/type", "PUT", "", "", ""},
		{"p", "admin", "/api/v1/dict/type/:id", "DELETE", "", "", ""},
		{"p", "admin", "/api/v1/posts", "GET", "", "", ""},
		{"p", "admin", "/api/v1/posts/:id", "GET", "", "", ""},
		{"p", "admin", "/api/v1/posts", "POST", "", "", ""},
		{"p", "admin", "/api/v1/posts", "PUT", "", "", ""},
		{"p", "admin", "/api/v1/posts/:id", "DELETE", "", "", ""},
		{"p", "admin", "/api/v1/menuids", "GET", "", "", ""},
		{"p", "admin", "/api/v1/loginlog", "GET", "", "", ""},
		{"p", "admin", "/api/v1/loginlog/:id", "DELETE", "", "", ""},
		{"p", "admin", "/api/v1/operlog", "GET", "", "", ""},
		{"p", "admin", "/api/v1/getinfo", "GET", "", "", ""},
		{"p", "admin", "/api/v1/roledatascope", "PUT", "", "", ""},
		{"p", "admin", "/api/v1/roleDeptTreeselect/:id", "GET", "", "", ""},
		{"p", "admin", "/api/v1/deptTree", "GET", "", "", ""},
		{"p", "admin", "/api/v1/configKey/:id", "GET", "", "", ""},
		{"p", "admin", "/api/v1/logout", "POST", "", "", ""},
		{"p", "admin", "/api/v1/user/avatar", "POST", "", "", ""},
		{"p", "admin", "/api/v1/user/pwd", "PUT", "", "", ""},
		{"p", "admin", "/api/v1/dict/typeoptionselect", "GET", "", "", ""},
		{"p", "admin", "/api/v1/sysjobList", "GET", "", "", ""},
		{"p", "admin", "/api/v1/sysjob/:id", "GET", "", "", ""},
		{"p", "admin", "/api/v1/sysjob", "POST", "", "", ""},
		{"p", "admin", "/api/v1/sysjob", "PUT", "", "", ""},
		{"p", "admin", "/api/v1/sysjob/:id", "DELETE", "", "", ""},
		{"p", "admin", "/api/v1/syssettingList", "GET", "", "", ""},
		{"p", "admin", "/api/v1/syssetting/:id", "GET", "", "", ""},
		{"p", "admin", "/api/v1/syssetting", "POST", "", "", ""},
		{"p", "admin", "/api/v1/syssetting", "PUT", "", "", ""},
		{"p", "admin", "/api/v1/syssetting/:id", "DELETE", "", "", ""},
	}

	db.Table("sys_casbin_rule").Create(list)
}
